name: Oh My Fish!
title: Oh My Fish!
description: The fish shell framework
paginate: 10

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "docs"
      type: "posts"
    values:
      layout: "docs-markdown"
      permalink: "docs/:title"
