name: Oh My Fish!
title: Oh My Fish!
description: The fish shell framework
#paginate: 10
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: shell

defaults:
  -
    scope:
      path: "docs"
      type: "posts"
    values:
      layout: "docs-markdown"
      permalink: "docs/:title"

gems:
  - jekyll-redirect-from
  - jemoji
